### ISSUE TITLE
PVC

### ISSUE THREAD

**Issue by mrtshoot** [mmz-srf/passbolt-helm#30]
I have set the default storageclass for my namespace but unfortunately when I ran  "helm -n passbolt install passbolt . -f values-fingerprint.yaml" I saw my pvc was in pending mode.

**Comment by michizubi-SRF** [comment]
Hey @mrtshoot 

What platform are you running this on? 
Some providers don't support the access mode ReadWriteMany which is configured as the default in the values.yaml (see https://github.com/mmz-srf/passbolt-helm/blob/master/values.yaml#L21).

You might need to change that to ReadWriteOnce

On a different note: We decided to mark our charts as deprecated since Passbolt released their own, official charts.
See https://github.com/passbolt/charts-passbolt
Maybe you want to try out the official charts.
